# -*- coding: utf-8 -*-
"""ECT_HW4_104403553_Python_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hsnj9Vh_R2kyTgmpKlFdNoch7pb_2h_5

# Python

## Import Packages
pandas and np資料前處理
sklearn 拿來切分資料集還有把一些東西encode<br>
"""

import pandas as pd
import numpy as np
from sklearn import preprocessing, metrics
from sklearn.model_selection import train_test_split

"""## 讀檔"""

titanic_df = pd.read_csv('Titanic.csv')  
titanic_df.info()

titanic_df.head()

"""## nanmedian
find the median of age ignoring nan values
"""

age_median = np.nanmedian(titanic_df["Age"])
print("age median: ",age_median)

"""## 將空值取代
空值會變成median
"""

new_Age = np.where(titanic_df["Age"].isnull(), age_median, titanic_df["Age"])
#print(new_Age)
titanic_df['Age'] = new_Age

"""## 把passengerid 跟cabin丟掉"""

titanic_df = titanic_df.drop(['PassengerId' , 'Cabin'],axis = 1)

"""## 把有空值得丟掉"""

titanic_df = titanic_df.dropna()

"""## encode一下 前幾個禮拜做過很多次了 不用再解釋了"""

label_encoder = preprocessing.LabelEncoder()
encoded_Name = label_encoder.fit_transform(titanic_df['Name'])
titanic_df['Name'] = encoded_Name
encoded_Sex = label_encoder.fit_transform(titanic_df['Sex'])
titanic_df['Sex'] = encoded_Sex
encoded_Ticket = label_encoder.fit_transform(titanic_df['Ticket'])
titanic_df['Ticket'] = encoded_Ticket
encoded_Embarked = label_encoder.fit_transform(titanic_df['Embarked'])
titanic_df['Embarked'] = encoded_Embarked

"""## 純粹自己檢查用的"""

titanic_df.head()

"""## 切分attribute跟 label"""

x=titanic_df.loc[:,['Pclass','Name','Age','SibSp','Parch','Ticket','Fare','Embarked']]
y=titanic_df.loc[:,['Survived']]

"""## 切分test train"""

train_X, test_X, train_y, test_y = train_test_split(x, y, test_size = 0.33)

"""## 開始learn一下"""

from sklearn.linear_model import LogisticRegression as LR
clf = LR(solver = 'liblinear').fit(train_X , train_y)

"""## 跑效果如何出來"""

predicted_test = clf.predict(test_X)
accuracy_test = metrics.accuracy_score(predicted_test, test_y)
print('accuracy: ',accuracy_test)

clf.score(test_X,test_y)

